<a href="https://colab.research.google.com/github/FaraazArsath/GUVI-Task2/blob/main/Guvi_Task_2_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
import numpy as np
np.zeros(10,dtype=int)  

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
import numpy as np
x=np.array([100,20,34,50,40])
print(x.size) # Gives size of the array
print(x.itemsize) # Gives memory size of one array elemment in bytes
print(x.size * x.itemsize) # Gives memory size of an array 
print(x.nbytes) # gives memory size of an array

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
import numpy as np
x=np.zeros(10,dtype=int)
x[4]=1
print(x)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
import numpy as np
x=np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
import numpy as np
x=np.array([100,30,50,80])
print(x[::-1])

[ 80  50  30 100]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
import numpy as np
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
import numpy as np
x = np.array([1,2,0,0,4,0])
print(np.nonzero(x))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
import numpy as np
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
import numpy as np
print(np.random.random((3,3,3)))

[[[0.03545289 0.90235347 0.70897157]
  [0.06637414 0.36284842 0.57027798]
  [0.7537304  0.54661302 0.88182448]]

 [[0.51924146 0.24120707 0.57913846]
  [0.31588822 0.09598302 0.65433506]
  [0.10602522 0.65849362 0.61084795]]

 [[0.65732708 0.37712721 0.03921749]
  [0.13028273 0.42197206 0.37313999]
  [0.29976782 0.33998759 0.77671525]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
import numpy as np
x=np.random.random((10,10))
y=x.min()
z=x.max()
print("minimum value is :",y)
print("maximum value is :",z)

minimum value is : 0.01319180552583299
maximum value is : 0.9586259743056347


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
import numpy as np
x=np.random.random(30)
print(x)
print("the mean value is ..")
print(np.mean(x))

[0.00964925 0.14508995 0.07765545 0.70303573 0.77841784 0.16803947
 0.81937392 0.80349211 0.6074441  0.54839997 0.71295485 0.90925386
 0.9982091  0.6363646  0.47888468 0.38728919 0.34633902 0.8301027
 0.52635984 0.31467796 0.84677353 0.88324709 0.13395398 0.05380205
 0.20425272 0.31142589 0.47250933 0.6418947  0.45445805 0.91845159]
the mean value is ..
0.5240600832610397


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
import numpy as np
x=np.ones((8,8))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
import numpy as np
x=np.random.random((3,3))
print(np.pad(x,pad_width=1))

[[0.         0.         0.         0.         0.        ]
 [0.         0.80500933 0.14533608 0.54103429 0.        ]
 [0.         0.05097846 0.4818113  0.07078698 0.        ]
 [0.         0.46806612 0.64399794 0.99544518 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
import numpy as np
x = np.random.random((5,5))
y = np.diag(np.arange(1,5),k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
import numpy as np
x = np.zeros((8,8),dtype='int')
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
import numpy as np
x=np.random.random((6,7,8))
print(np.unravel_index([100],(6,7,8)))

(array([1]), array([5]), array([4]))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
import numpy as np
x=np.array([[1,0],[0,1]])
print(np.tile(x,(4,4)))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
import numpy as np
x = np.random.random((5,5))
min,max=x.min(),x.max()
y=x-min/min-max
print(y)

[[-1.93477219 -1.53006165 -1.68613758 -1.35957978 -1.15510492]
 [-1.28332805 -1.42208105 -1.91333054 -1.63255482 -1.56104659]
 [-1.90863053 -1.86902078 -1.15220347 -1.40279124 -1.84854779]
 [-1.13255093 -1.01208883 -1.22248382 -1.         -1.17885716]
 [-1.1879652  -1.94280486 -1.45359424 -1.36981985 -1.29805112]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
import numpy as np

color = np.dtype([('R', 'B'),
                  ('G', 'B'),
                  ('B', 'B'),
                  ('A', 'B')])
print(type(color))
print(color.itemsize)
print(color.name)

<class 'numpy.dtype[void]'>
4
void32


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
import numpy as np
x=np.random.random((5,3))
y=np.random.random((3,2))
z=np.dot(x,y)
print(z)

[[0.89285444 0.69675501]
 [0.77617626 0.7205391 ]
 [1.36075017 1.23338172]
 [0.93335199 0.77725802]
 [1.35152499 1.10421531]]


In [ ]:
import numpy as np
x=np.random.random((5,3))
y=np.random.random((3,2))
z=x @ y
print(z)

[[0.73872538 0.26457327]
 [0.75557102 0.31875025]
 [1.20887012 0.54179096]
 [1.06196571 0.49264787]
 [1.40222885 0.70314904]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
import numpy as np
x=np.arange(12)
x[(x>3) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
[-9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
import numpy as np
x=np.random.uniform(-1,1,5)
print('Input float array using uniform distribution is : ')
print(x)
print('Rounding off float array :')
print(np.round(x))
print('Rounding off float array away from zero :')
print(np.copysign(np.ceil(np.abs(x)),x))

Input float array using uniform distribution is : 
[ 0.05914169  0.13468643 -0.76259151 -0.0300659   0.839639  ]
Rounding off float array :
[ 0.  0. -1. -0.  1.]
Rounding off float array away from zero :
[ 1.  1. -1. -1.  1.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
import numpy as np
# creating the input arrays
a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8])

# finding the intersect of the two arrays
print(np.intersect1d(a, b))

# creating the input arrays
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[1,2,6], [4,5,6]])

# finding the intersect of the two arrays
print(np.intersect1d(c, d))

# creating the input arrays
e = np.array([[1,2,3], [7,8,9]])
f = np.array([[1,2,7], [4,5,6]])

# finding the intersect of the two arrays
print(np.intersect1d(e, f, return_indices = True))

[]
[1 2 4 5 6]
(array([1, 2, 7]), array([0, 1, 3]), array([0, 1, 2]))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
import numpy as np

# ignoring warning using np.seterr

np.seterr(all="ignore")
x=np.sqrt(-1)
print(x)

# ignoring warning using np.errstate 

with np.errstate(invalid='ignore'):
  x=np.sqrt(-1)
  print(x)



nan
nan


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
import numpy as np

today = np.datetime64('today','D')
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(yesterday)
print(today)
print(tomorrow)

2022-08-08
2022-08-09
2022-08-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
import numpy as np

np.arange('2016-07','2016-08', dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
import numpy as np

A = np.arange(10,dtype='float')
print("Input array A is :",A)
B = np.arange(10,20, dtype ='float')
print("Input array B is :",B)


np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
print("Output array ((A+B)*(-A/2)) is : ")
np.multiply(B,A,out=A)


Input array A is : [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Input array B is : [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Output array ((A+B)*(-A/2)) is : 


array([  -0.,   -6.,  -14.,  -24.,  -36.,  -50.,  -66.,  -84., -104.,
       -126.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
import numpy as np
x = np.random.uniform(1,5,5)
print("input array is :",x)
print(x-x%1)
print(np.floor(x))
print(np.ceil(x)-1)
print(x.astype(int))
print(np.trunc(x))

input array is : [2.86311818 4.49317825 4.51582345 1.47239653 1.12263492]
[2. 4. 4. 1. 1.]
[2. 4. 4. 1. 1.]
[2. 4. 4. 1. 1.]
[2 4 4 1 1]
[2. 4. 4. 1. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5))
y=np.arange(5)
z = np.add(x,y)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
# Creating a generator function to generate 10 integers
def generator():
  for x in range(10):
    yield x*x


# Building array 
y = np.fromiter(generator(),dtype=int)
print(y)

[ 0  1  4  9 16 25 36 49 64 81]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(0,1,num=12)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(10)
x.sort()
print(x)

[0.06837832 0.14928682 0.2568025  0.4105324  0.44281098 0.49075869
 0.6325999  0.67549933 0.70229975 0.84734257]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
import numpy as np

x = np.arange(10)
print("Input array is :",x)
print("Sum of array is :",np.add.reduce(x))

Input array is : [0 1 2 3 4 5 6 7 8 9]
Sum of array is : 45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.array([1, 2, 5, 7, 10])
B = np.array([1, 2, 5,10, 10])

print("Is two arrays are element-wise equal within a tolerance :", np.allclose(A,B,atol=3))
print("Is two arrays have the same shape and elements :", np.array_equal(A,B))

Is two arrays are element-wise equal within a tolerance : True
Is two arrays have the same shape and elements : False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
A = np.array([1, 2, 3, 4, 5])
print("Input array is :",A)
# Mutating the input array
A[1] = 7
print("Mutated input array :",A)
A.flags.writeable = False
print("Changed Input array to immutable (read-only)")
print(A)

Input array is : [1 2 3 4 5]
Mutated input array : [1 7 3 4 5]
Changed Input array to immutable (read-only)
[1 7 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
import numpy as np

# 10x2 matrix represnting cartesian coordinates
z = np.random.random((10,2))
# Cartesian coordinates x and y are 
x = z[:,0] 
y = z[:,1]

'''To convert from Cartesian Coordinates (x,y) to Polar Coordinates (r,θ):
r = √ ( x2 + y2 ) , θ = tan-1 ( y / x )'''

r = np.sqrt(x**2 + y**2)
θ = np.arctan2(y,x)
print("Polar coordinates are: ")
print("r : ",r)
print("θ : ",θ)

Polar coordinates are: 
r :  [1.11298011 0.07315499 0.84694023 0.94808098 0.78555111 0.38599433
 0.47481831 0.54540897 0.89953883 1.00448483]
θ :  [0.76485156 1.22181191 1.54329479 0.22625719 0.97908254 1.39716296
 0.56531753 0.10132388 1.56692196 0.92884975]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
import numpy as np

x = np.arange(10)
print("Input Array is ",x)
x[np.argmax(x)] = 0

print("Replaced maximumm value by 0 :",x)


Input Array is  [0 1 2 3 4 5 6 7 8 9]
Replaced maximumm value by 0 : [0 1 2 3 4 5 6 7 8 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
import numpy as np

# creating a structured array using a compound data type with x and y coordinates
z = np.ones((3,3),np.dtype([('x',float),('y',float)]))

# creating a mesh using np.meshgrid - Returns coordinate matrices from coordinate vectors

a = np.linspace(0,1,3)
b = np.linspace(0,1,3)

av, bv = np.meshgrid(a,b)

z['x'] , z['y'] = av , bv

print(z)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


In [ ]:
a = np.linspace(0,1,3)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
import numpy as name
x = np.linspace(2,5,5)
y = np.linspace(3,9,5)

# Constructing the Cauchy matrix C (Cij =1/(xi - yj))
C = 1 / (np.subtract.outer(x,y))

print(C)

[[-1.         -0.4        -0.25       -0.18181818 -0.14285714]
 [-4.         -0.57142857 -0.30769231 -0.21052632 -0.16      ]
 [ 2.         -1.         -0.4        -0.25       -0.18181818]
 [ 0.8        -4.         -0.57142857 -0.30769231 -0.21052632]
 [ 0.5         2.         -1.         -0.4        -0.25      ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
print("Min & Max value for dtype 'int' ")
for dtype in [np.int8,np.int16,np.int32,np.int64]:
  print("Minimum value:",np.iinfo(dtype).min, ", Maximum Value:",np.iinfo(dtype).max)
print('-----------------')
print("Min & Max value for dtype 'float' ")
for dtype in [np.float16,np.float32,np.float64]:
  print("Minimum value:",np.finfo(dtype).min, ", Maximum Value:",np.finfo(dtype).max)

Min & Max value for dtype 'int' 
Minimum value: -128 , Maximum Value: 127
Minimum value: -32768 , Maximum Value: 32767
Minimum value: -2147483648 , Maximum Value: 2147483647
Minimum value: -9223372036854775808 , Maximum Value: 9223372036854775807
-----------------
Min & Max value for dtype 'float' 
Minimum value: -65500.0 , Maximum Value: 65500.0
Minimum value: -3.4028235e+38 , Maximum Value: 3.4028235e+38
Minimum value: -1.7976931348623157e+308 , Maximum Value: 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
import numpy as np
# To print all values of array 
np.set_printoptions(threshold=float('inf'))
x = np.ones((50,50))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
import numpy as np

# creating input vector
x = np.array([1,4,6,7,8,6,10])
print("Input Vector: ",x)

# creating scalar value
y = np.random.uniform(0,6)
print("Input scalar value to copare with vector :",y)

z = (np.abs(x-y)).argmin()
print("Closest value (to a given scalar) in a vector :",x[z])
print("Index of the closest value is :",z)

Input Vector:  [ 1  4  6  7  8  6 10]
Input scalar value to copare with vector : 3.4201130375654447
Closest value (to a given scalar) in a vector : 4
Index of the closest value is : 1


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
import numpy as np

# creating a structured array using a compound data type with position(x,y) and color(r,g,b)
z = np.ones(3,np.dtype([('position',[('x',float),
                                         ('y',float)]),
                            ('color',[('r',float),
                                      ('g',float),
                                      ('b',float)])]))
print(z)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.))]
[1. 1. 1.]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
import numpy as np

x = np.arange(5,dtype = np.float32)
x = x.astype(np.int32 , copy = False)
print(x)

[0 1 2 3 4]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)